image: node:18

pipelines:
  branches:
    staging:
      - step:
          name: Deployment to QA server
          deployment: Staging
          caches:
            - node
          script:
          - wget -O - https://raw.githubusercontent.com/shahzaib-sheikh/replace-env-vars/master/replace-env-vars.sh | bash -s .env.example .env SECRETS
          - cat .env
          - wget -O - https://raw.githubusercontent.com/shahzaib-sheikh/replace-env-vars/master/replace-env-vars.sh | bash -s  docker-compose.example.yml docker-compose.yml SECRETS
          - cat docker-compose.yml
          - yarn install
          - yarn run build
          - ssh ubuntu@54.151.24.157 "mkdir -p ~/clevis-be-stg"
          - rsync -av ./package.json ./package-lock.json ./.env ./dist ./ormconfig.js ./ecosystem.config.js ./docker-compose.yml -e ssh ubuntu@54.151.24.157:~/clevis-be-stg
          - ssh ubuntu@54.151.24.157 "cd ~/clevis-be-stg && yarn ci --production"
          - ssh ubuntu@54.151.24.157 "cd ~/clevis-be-stg  && sudo docker-compose -p STAGING up -d"
          - ssh ubuntu@54.151.24.157 "cd ~/clevis-be-stg && yarn prisma:dev:deploy"
          - ssh ubuntu@54.151.24.157 "cd ~/clevis-be-stg && yarn build"
          - ssh ubuntu@54.151.24.157 "cd ~/clevis-be-stg && yarn start"

