version: '3.8'
services:
  dev-db:
    image: kartoza/postgis:14-3.2
    restart: always
    ports:
      - 5434:5432
    volumes:
      - pgdb-clevis:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: SECRETS_POSTGRES_USER
      POSTGRES_PASSWORD: SECRETS_POSTGRES_PASSWORD
      POSTGRES_DB: SECRETS_POSTGRES_DB
    networks:
      - freecodecamp
  redis:
    container_name: clevis_redis
    image: bitnami/redis:7.0.11
    restart: always
    ports:
      - 6380:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'clevis_redis_data:/var/lib/docker/volumes/clevis_redis_data/_data'  
networks:
  freecodecamp:
volumes:
  pgdb-clevis:
    external: true
  clevis_redis_data:
    external: true
