version: '3.8'
services:
  dev-db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5434:5432
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: click123$
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
volumes:
  db:
    driver: local
