version: '3.8'
services:
  dev-db:
    image: kartoza/postgis:14-3.2
    restart: always
    ports:
      - 5434:5432
    volumes:
      - pgdb-clevis:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: SECRETS_POSTGRES_USER
      POSTGRES_PASSWORD: SECRETS_POSTGRES_PASSWORD
      POSTGRES_DB: SECRETS_POSTGRES_DB
    networks:
      - freecodecamp
networks:
  freecodecamp:
volumes:
  pgdb-clevis:
    external: true
  clevis_redis_data:
    external: true
