import { ServiceType, UserType } from '@prisma/client';

export const roles = [
  {
    name: 'ADMIN',
    userType: UserType.ADMIN,
  },
  {
    name: 'CUSTOMER',
    userType: UserType.CUSTOMER,
  },
  {
    name: 'RIDER',
    userType: UserType.RIDER,
  },
  {
    name: 'VENDOR',
    userType: UserType.VENDOR,
  },
];

const AUTHENTICATED_ROUTES = {
  ADMIN_DASHBOARD: 'dashboard',
  MY_SERVICES: 'my-services',
  MY_SERVICES_DETAIL: 'detail/',
  ADD_SERVICES: 'add-service',
  EDIT_SERVICES: 'edit-service/',
  SERVICE_BOOKINGS: 'service-bookings',
  MY_EARNINGS: 'my-earnings',
  JOB_REQUESTS: 'job-requests',
  ABOUT_US: 'about-us',
  TERMS_CONDITION: 'terms-condition',
  HELP_SUPPORT: 'help-support',
  PROFILE: 'profile',
};

export const routes = [
  {
    icon: 'dashboard',
    label: 'dashboard',
    linkTo: '/dashboard',
    selectedOptionKey: 'dashboard',
    routeName: 'dashboard',
  },
  {
    icon: 'vendor-dashboard',
    label: 'dashboard',
    linkTo: '/dashboard',
    selectedOptionKey: 'dashboard',
    routeName: 'dashboard',
  },
  {
    icon: 'customer-management',
    label: 'customer-management',
    linkTo: '/customer-management',
    selectedOptionKey: 'customer-management',
    routeName: 'customer-management',
  },
  {
    icon: 'vendor-management',
    label: 'vendor-management',
    linkTo: '/vendor-management',
    selectedOptionKey: 'vendor-management',
    routeName: 'vendor-management',
  },
  {
    icon: 'rider-management',
    label: 'rider-management',
    linkTo: '/rider-management',
    selectedOptionKey: 'rider-management',
    routeName: 'rider-management',
  },
  {
    icon: 'bookings-management',
    label: 'bookings-management',
    linkTo: '/bookings-management',
    selectedOptionKey: 'bookings-management',
    routeName: 'bookings-management',
  },
  {
    icon: 'payments-management',
    label: 'payments-management',
    linkTo: '/payments-management',
    selectedOptionKey: 'payments-management',
    routeName: 'payments-management',
  },
  {
    icon: 'service-management',
    label: 'service-management',
    linkTo: '/service-management',
    selectedOptionKey: 'service-management',
    routeName: 'service-management',
  },
  {
    icon: 'settings',
    label: 'settings',
    linkTo: '/settings',
    selectedOptionKey: 'settings',
    routeName: 'settings',
  },
  {
    icon: 'vendor-services',
    label: 'My services',
    linkTo: '/vendor/services',
    selectedOptionKey: 'vendor-services',
    routeName: 'vendor-services',
  },
  {
    icon: 'vendor-bookings',
    label: 'Service Bookings',
    linkTo: '/vendor/bookings',
    selectedOptionKey: 'vendor-bookings',
    routeName: 'vendor-bookings',
  },
  {
    icon: 'payments-management',
    label: 'My Payments',
    linkTo: '/payments',
    selectedOptionKey: 'payments',
    routeName: 'payments',
  },
  {
    icon: 'job-requests',
    label: 'Job Requests',
    linkTo: '/job-requests',
    selectedOptionKey: 'payments',
    routeName: 'payments',
  },
  {
    icon: 'earnings',
    label: 'Earnings',
    linkTo: '/earnings',
    selectedOptionKey: 'earnings',
    routeName: 'earnings',
  },

  {
    label: 'Dashboard',
    linkTo: AUTHENTICATED_ROUTES.ADMIN_DASHBOARD,
    selectedOptionKey: 'dashboard',
    icon: '<DashboardIcon />',
  },
  {
    label: 'Job Requests',
    linkTo: AUTHENTICATED_ROUTES.JOB_REQUESTS,
    selectedOptionKey: 'job-requests',
    icon: '<JobRequestIcon />',
  },
  {
    label: 'Earnings',
    linkTo: AUTHENTICATED_ROUTES.MY_EARNINGS,
    selectedOptionKey: 'my-earnings',
    icon: '<EarningsIcon />',
  },
];

export const subcategories = [
  { subCategoryName: 'Cotton', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Linen', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Silk', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Lace', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Satin', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Polyester', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Knit', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Wool', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Rayon', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Blends', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Cotton Lawn', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Jersey', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Chiffon', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Georgette', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Nylon', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Leather', serviceType: ServiceType.LAUNDRY },
  {
    subCategoryName: 'Synthetic (Microfiber)',
    serviceType: ServiceType.LAUNDRY,
  },
  { subCategoryName: 'Flannel', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Denim', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Polar Fleece', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Lawn', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Cashmere', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Pique Knit', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Velvet', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Corduroy', serviceType: ServiceType.LAUNDRY },
  { subCategoryName: 'Spandex', serviceType: ServiceType.LAUNDRY },
];

export const categories = [
  { categoryName: 'Sedan', serviceType: ServiceType.CAR_WASH },
  { categoryName: 'Minivan', serviceType: ServiceType.CAR_WASH },
  { categoryName: 'Electric Car', serviceType: ServiceType.CAR_WASH },
  { categoryName: 'Hatchback', serviceType: ServiceType.CAR_WASH },
  { categoryName: 'Convertible', serviceType: ServiceType.CAR_WASH },
  { categoryName: 'Coupe', serviceType: ServiceType.CAR_WASH },
  { categoryName: 'Crossover SUVS', serviceType: ServiceType.CAR_WASH },
  { categoryName: 'Small Sized SUVS', serviceType: ServiceType.CAR_WASH },
  { categoryName: 'Full Sized SUVS', serviceType: ServiceType.CAR_WASH },
  { categoryName: 'Hat', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Cap', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Beanie', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Headband', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Gloves', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Mittens', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Belt', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Tie', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Bow tie', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Necktie', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Pocket square', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Bandana', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Turbans', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Fezes', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Kaffiyeh', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Mishlah', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Burqa', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Thawb', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Tagiyah', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Salwar', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Curtain', serviceType: ServiceType.LAUNDRY },
  { categoryName: 'Carpet', serviceType: ServiceType.LAUNDRY },
];
