export const byYearArray = [
  {
    month: 'Jan',
    laundryVendors: 0,
    carWashVendors: 0,
  },
  {
    month: 'Feb',
    laundryVendors: 0,
    carWashVendors: 0,
  },
  {
    month: 'Mar',
    laundryVendors: 0,
    carWashVendors: 0,
  },
  {
    month: 'Apr',
    laundryVendors: 0,
    carWashVendors: 0,
  },
  {
    month: 'May',
    laundryVendors: 0,
    carWashVendors: 0,
  },
  {
    month: 'Jun',
    laundryVendors: 0,
    carWashVendors: 0,
  },
  {
    month: 'Jul',
    laundryVendors: 0,
    carWashVendors: 0,
  },
  {
    month: 'Aug',
    laundryVendors: 0,
    carWashVendors: 0,
  },
  {
    month: 'Sep',
    laundryVendors: 0,
    carWashVendors: 0,
  },
  {
    month: 'Oct',
    laundryVendors: 0,
    carWashVendors: 0,
  },
  {
    month: 'Nov',
    laundryVendors: 0,
    carWashVendors: 0,
  },
  {
    month: 'Dec',
    laundryVendors: 0,
    carWashVendors: 0,
  },
];

export const byMonthArray = [
  { day: 1, laundryVendors: 0, carWashVendors: 0 },
  { day: 2, laundryVendors: 0, carWashVendors: 0 },
  { day: 3, laundryVendors: 0, carWashVendors: 0 },
  { day: 4, laundryVendors: 0, carWashVendors: 0 },
  { day: 5, laundryVendors: 0, carWashVendors: 0 },
  { day: 6, laundryVendors: 0, carWashVendors: 0 },
  { day: 7, laundryVendors: 0, carWashVendors: 0 },
  { day: 8, laundryVendors: 0, carWashVendors: 0 },
  { day: 9, laundryVendors: 0, carWashVendors: 0 },
  { day: 10, laundryVendors: 0, carWashVendors: 0 },
  { day: 11, laundryVendors: 0, carWashVendors: 0 },
  { day: 12, laundryVendors: 0, carWashVendors: 0 },
  { day: 13, laundryVendors: 0, carWashVendors: 0 },
  { day: 14, laundryVendors: 0, carWashVendors: 0 },
  { day: 15, laundryVendors: 0, carWashVendors: 0 },
  { day: 16, laundryVendors: 0, carWashVendors: 0 },
  { day: 17, laundryVendors: 0, carWashVendors: 0 },
  { day: 18, laundryVendors: 0, carWashVendors: 0 },
  { day: 19, laundryVendors: 0, carWashVendors: 0 },
  { day: 20, laundryVendors: 0, carWashVendors: 0 },
  { day: 21, laundryVendors: 0, carWashVendors: 0 },
  { day: 22, laundryVendors: 0, carWashVendors: 0 },
  { day: 23, laundryVendors: 0, carWashVendors: 0 },
  { day: 24, laundryVendors: 0, carWashVendors: 0 },
  { day: 25, laundryVendors: 0, carWashVendors: 0 },
  { day: 26, laundryVendors: 0, carWashVendors: 0 },
  { day: 27, laundryVendors: 0, carWashVendors: 0 },
  { day: 28, laundryVendors: 0, carWashVendors: 0 },
  { day: 29, laundryVendors: 0, carWashVendors: 0 },
  { day: 30, laundryVendors: 0, carWashVendors: 0 },
  { day: 31, laundryVendors: 0, carWashVendors: 0 },
];
